# Generated by Django 5.2.8 on 2025-12-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='revision',
            new_name='revisions',
        ),
    ]
