# Generated by Django 5.2.8 on 2025-12-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='in_progress', error_messages={'invalid_choice': 'Status must be one of: in_progress, completed, cancelled.'}, max_length=50),
        ),
    ]
